# syntax=docker/dockerfile:1.7

ARG NODE_VERSION=24-bookworm-slim
ARG PNPM_VERSION=11.1.3

FROM node:${NODE_VERSION} AS base
WORKDIR /app

ENV PNPM_HOME=/pnpm
ENV PATH=$PNPM_HOME:$PATH

ARG PNPM_VERSION
RUN npm install --global pnpm@${PNPM_VERSION}

FROM base AS deps

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json tsconfig.base.json ./
COPY apps/api/package.json apps/api/package.json
COPY apps/web/package.json apps/web/package.json
COPY packages/core/package.json packages/core/package.json
COPY packages/credentials/package.json packages/credentials/package.json
COPY packages/db/package.json packages/db/package.json
COPY packages/github/package.json packages/github/package.json
COPY packages/mcp-gateway/package.json packages/mcp-gateway/package.json
COPY packages/model-router/package.json packages/model-router/package.json
COPY packages/observability/package.json packages/observability/package.json
COPY packages/runtime/package.json packages/runtime/package.json
COPY packages/sandbox/package.json packages/sandbox/package.json
COPY packages/slack/package.json packages/slack/package.json
COPY packages/worker/package.json packages/worker/package.json

RUN pnpm install --frozen-lockfile

FROM deps AS source
COPY . .

FROM source AS api_worker_build
RUN pnpm --filter @bek/api... --filter @bek/worker... build
RUN pnpm --filter @bek/api deploy --legacy --prod /out/api \
  && pnpm --filter @bek/worker deploy --legacy --prod /out/worker

FROM source AS migrate
ENV NODE_ENV=production
USER node
CMD ["pnpm", "db:migrate"]

FROM node:${NODE_VERSION} AS runtime_base
WORKDIR /app
RUN node -e 'const fs=require("node:fs");const script="Y29uc3QgZnMgPSByZXF1aXJlKCJub2RlOmZzIik7CmNvbnN0IHBhdGggPSByZXF1aXJlKCJub2RlOnBhdGgiKTsKCmNvbnN0IHJvb3QgPSBwYXRoLnJlc29sdmUocHJvY2Vzcy5hcmd2WzJdID8/ICIvYXBwIik7CmNvbnN0IHVucmVzb2x2ZWQgPSBbXTsKbGV0IHBhdGNoZWRGaWxlcyA9IDA7CgpmdW5jdGlvbiB3YWxrKGRpciwgdmlzaXQpIHsKICBmb3IgKGNvbnN0IGVudHJ5IG9mIGZzLnJlYWRkaXJTeW5jKGRpciwgeyB3aXRoRmlsZVR5cGVzOiB0cnVlIH0pKSB7CiAgICBjb25zdCBmdWxsID0gcGF0aC5qb2luKGRpciwgZW50cnkubmFtZSk7CiAgICBpZiAoZW50cnkuaXNEaXJlY3RvcnkoKSkgewogICAgICB3YWxrKGZ1bGwsIHZpc2l0KTsKICAgIH0gZWxzZSBpZiAoZW50cnkuaXNGaWxlKCkpIHsKICAgICAgdmlzaXQoZnVsbCk7CiAgICB9CiAgfQp9CgpmdW5jdGlvbiBydW50aW1lU3BlY2lmaWVyKGZyb21GaWxlLCBzcGVjaWZpZXIpIHsKICBpZiAoIXNwZWNpZmllci5zdGFydHNXaXRoKCIuLyIpICYmICFzcGVjaWZpZXIuc3RhcnRzV2l0aCgiLi4vIikpIHsKICAgIHJldHVybiBzcGVjaWZpZXI7CiAgfQogIGlmIChwYXRoLmV4dG5hbWUoc3BlY2lmaWVyKSkgewogICAgcmV0dXJuIHNwZWNpZmllcjsKICB9CgogIGNvbnN0IGNhbmRpZGF0ZSA9IHBhdGgucmVzb2x2ZShwYXRoLmRpcm5hbWUoZnJvbUZpbGUpLCBzcGVjaWZpZXIpOwogIGlmIChmcy5leGlzdHNTeW5jKGNhbmRpZGF0ZSArICIuanMiKSkgewogICAgcmV0dXJuIHNwZWNpZmllciArICIuanMiOwogIH0KICBpZiAoZnMuZXhpc3RzU3luYyhwYXRoLmpvaW4oY2FuZGlkYXRlLCAiaW5kZXguanMiKSkpIHsKICAgIHJldHVybiBzcGVjaWZpZXIgKyAiL2luZGV4LmpzIjsKICB9CgogIHJldHVybiBzcGVjaWZpZXI7Cn0KCmZ1bmN0aW9uIHNob3VsZFBhdGNoSnMoZmlsZSkgewogIHJldHVybiAoCiAgICBmaWxlLmVuZHNXaXRoKCIuanMiKSAmJgogICAgKGZpbGUuc3RhcnRzV2l0aChwYXRoLmpvaW4ocm9vdCwgImRpc3QiKSArIHBhdGguc2VwKSB8fAogICAgICAoZmlsZS5pbmNsdWRlcyhwYXRoLnNlcCArICJub2RlX21vZHVsZXMiICsgcGF0aC5zZXApICYmCiAgICAgICAgZmlsZS5pbmNsdWRlcyhwYXRoLnNlcCArICJub2RlX21vZHVsZXMiICsgcGF0aC5zZXAgKyAiQGJlayIgKyBwYXRoLnNlcCkgJiYKICAgICAgICBmaWxlLmluY2x1ZGVzKHBhdGguc2VwICsgImRpc3QiICsgcGF0aC5zZXApKSkKICApOwp9CgpmdW5jdGlvbiBwYXRjaEpzSW1wb3J0cyhmaWxlKSB7CiAgY29uc3Qgc291cmNlID0gZnMucmVhZEZpbGVTeW5jKGZpbGUsICJ1dGY4Iik7CiAgY29uc3QgbmV4dCA9IHNvdXJjZQogICAgLnJlcGxhY2UoCiAgICAgIC8oXGIoPzpleHBvcnRccysoPzpcKnxce1tefV0qXH0pXHMrZnJvbXxmcm9tKVxzKlsiJ10pKFwuXC4/XC9bXiInXSspKFsiJ10pL2csCiAgICAgIChfbWF0Y2gsIHByZWZpeCwgc3BlY2lmaWVyLCBzdWZmaXgpID0+CiAgICAgICAgcHJlZml4ICsgcnVudGltZVNwZWNpZmllcihmaWxlLCBzcGVjaWZpZXIpICsgc3VmZml4LAogICAgKQogICAgLnJlcGxhY2UoCiAgICAgIC8oXGJpbXBvcnRccypcKFxzKlsiJ10pKFwuXC4/XC9bXiInXSspKFsiJ11ccypcKSkvZywKICAgICAgKF9tYXRjaCwgcHJlZml4LCBzcGVjaWZpZXIsIHN1ZmZpeCkgPT4KICAgICAgICBwcmVmaXggKyBydW50aW1lU3BlY2lmaWVyKGZpbGUsIHNwZWNpZmllcikgKyBzdWZmaXgsCiAgICApOwoKICBpZiAobmV4dCAhPT0gc291cmNlKSB7CiAgICBmcy53cml0ZUZpbGVTeW5jKGZpbGUsIG5leHQpOwogICAgcGF0Y2hlZEZpbGVzICs9IDE7CiAgfQp9CgpmdW5jdGlvbiBtYXBFeHBvcnRzKHZhbHVlKSB7CiAgaWYgKHR5cGVvZiB2YWx1ZSA9PT0gInN0cmluZyIpIHsKICAgIHJldHVybiB2YWx1ZS5yZXBsYWNlKC9eXC5cL3NyY1wvKC4rKVwudHMkLywgIi4vZGlzdC8kMS5qcyIpOwogIH0KICBpZiAoQXJyYXkuaXNBcnJheSh2YWx1ZSkpIHsKICAgIHJldHVybiB2YWx1ZS5tYXAobWFwRXhwb3J0cyk7CiAgfQogIGlmICh2YWx1ZSAmJiB0eXBlb2YgdmFsdWUgPT09ICJvYmplY3QiKSB7CiAgICByZXR1cm4gT2JqZWN0LmZyb21FbnRyaWVzKAogICAgICBPYmplY3QuZW50cmllcyh2YWx1ZSkubWFwKChba2V5LCBuZXN0ZWRdKSA9PiBba2V5LCBtYXBFeHBvcnRzKG5lc3RlZCldKSwKICAgICk7CiAgfQogIHJldHVybiB2YWx1ZTsKfQoKZnVuY3Rpb24gcGF0Y2hCZWtQYWNrYWdlKGZpbGUpIHsKICBjb25zdCBwa2cgPSBKU09OLnBhcnNlKGZzLnJlYWRGaWxlU3luYyhmaWxlLCAidXRmOCIpKTsKICBpZiAoIXBrZy5uYW1lPy5zdGFydHNXaXRoKCJAYmVrLyIpIHx8ICFwa2cuZXhwb3J0cykgewogICAgcmV0dXJuOwogIH0KCiAgY29uc3QgYmVmb3JlID0gSlNPTi5zdHJpbmdpZnkocGtnLmV4cG9ydHMpOwogIHBrZy5leHBvcnRzID0gbWFwRXhwb3J0cyhwa2cuZXhwb3J0cyk7CiAgaWYgKEpTT04uc3RyaW5naWZ5KHBrZy5leHBvcnRzKSAhPT0gYmVmb3JlKSB7CiAgICBmcy53cml0ZUZpbGVTeW5jKGZpbGUsIEpTT04uc3RyaW5naWZ5KHBrZywgbnVsbCwgMikgKyAiXG4iKTsKICAgIHBhdGNoZWRGaWxlcyArPSAxOwogIH0KfQoKZnVuY3Rpb24gdmVyaWZ5SnMoZmlsZSkgewogIGNvbnN0IHNvdXJjZSA9IGZzLnJlYWRGaWxlU3luYyhmaWxlLCAidXRmOCIpOwogIGZvciAoY29uc3QgcmVnZXggb2YgWwogICAgL1xiKD86ZXhwb3J0XHMrKD86XCp8XHtbXn1dKlx9KVxzK2Zyb218ZnJvbSlccypbIiddKFwuXC4/XC9bXiInXSspWyInXS9nLAogICAgL1xiaW1wb3J0XHMqXChccypbIiddKFwuXC4/XC9bXiInXSspWyInXVxzKlwpL2csCiAgXSkgewogICAgZm9yIChjb25zdCBtYXRjaCBvZiBzb3VyY2UubWF0Y2hBbGwocmVnZXgpKSB7CiAgICAgIGNvbnN0IHNwZWNpZmllciA9IG1hdGNoWzFdOwogICAgICBpZiAoIXNwZWNpZmllciB8fCBwYXRoLmV4dG5hbWUoc3BlY2lmaWVyKSkgewogICAgICAgIGNvbnRpbnVlOwogICAgICB9CiAgICAgIGNvbnN0IGNhbmRpZGF0ZSA9IHBhdGgucmVzb2x2ZShwYXRoLmRpcm5hbWUoZmlsZSksIHNwZWNpZmllcik7CiAgICAgIGlmIChmcy5leGlzdHNTeW5jKGNhbmRpZGF0ZSArICIuanMiKSB8fCBmcy5leGlzdHNTeW5jKHBhdGguam9pbihjYW5kaWRhdGUsICJpbmRleC5qcyIpKSkgewogICAgICAgIHVucmVzb2x2ZWQucHVzaChmaWxlICsgIjogIiArIHNwZWNpZmllcik7CiAgICAgIH0KICAgIH0KICB9Cn0KCndhbGsocm9vdCwgKGZpbGUpID0+IHsKICBpZiAoc2hvdWxkUGF0Y2hKcyhmaWxlKSkgewogICAgcGF0Y2hKc0ltcG9ydHMoZmlsZSk7CiAgfQogIGlmIChmaWxlLmVuZHNXaXRoKCJwYWNrYWdlLmpzb24iKSkgewogICAgcGF0Y2hCZWtQYWNrYWdlKGZpbGUpOwogIH0KfSk7Cgp3YWxrKHJvb3QsIChmaWxlKSA9PiB7CiAgaWYgKHNob3VsZFBhdGNoSnMoZmlsZSkpIHsKICAgIHZlcmlmeUpzKGZpbGUpOwogIH0KfSk7CgppZiAodW5yZXNvbHZlZC5sZW5ndGggPiAwKSB7CiAgdGhyb3cgbmV3IEVycm9yKCJVbnJlc29sdmVkIHJ1bnRpbWUgSlMgaW1wb3J0czpcbiIgKyB1bnJlc29sdmVkLmpvaW4oIlxuIikpOwp9Cgpjb25zb2xlLmxvZygiTm9ybWFsaXplZCBCZWsgcnVudGltZSBKUyAoIiArIHBhdGNoZWRGaWxlcyArICIgZmlsZXMgY2hhbmdlZCkuIik7Cg==";fs.writeFileSync("/usr/local/bin/normalize-bek-runtime.cjs",Buffer.from(script,"base64"));fs.chmodSync("/usr/local/bin/normalize-bek-runtime.cjs",0o755);'

FROM runtime_base AS api
ENV NODE_ENV=production
ENV BEK_API_PORT=4317
COPY --from=api_worker_build --chown=node:node /out/api ./
RUN node /usr/local/bin/normalize-bek-runtime.cjs /app
EXPOSE 4317
USER node
CMD ["node", "dist/index.js"]

FROM runtime_base AS worker
ENV NODE_ENV=production
COPY --from=api_worker_build --chown=node:node /out/worker ./
RUN node /usr/local/bin/normalize-bek-runtime.cjs /app
USER node
CMD ["node", "dist/runner.js"]

FROM source AS web_build
RUN pnpm --filter @bek/web... build
RUN pnpm --filter @bek/web deploy --legacy --prod /out/web

FROM node:${NODE_VERSION} AS web
WORKDIR /app
ENV NODE_ENV=production
ENV BEK_WEB_PORT=5173
COPY --from=web_build --chown=node:node /out/web/dist ./dist
COPY --from=source --chown=node:node /app/apps/web/server.mjs ./server.mjs
EXPOSE 5173
USER node
CMD ["node", "server.mjs"]
