import { describe, expect, it } from "vitest";
import {
  executeGitHubDraftPullRequestWorkflowPlan,
  type GitHubDraftPullRequestWorkflowExecutionClient,
  type GitHubWorkflowExecutionAuth,
} from "./execution";
import { FakeGitHubClient } from "./fake-client";
import {
  FakeGitHubInstallationTokenProvider,
  type GitHubInstallationTokenProvider,
} from "./tokens";
import { createGitHubDraftPullRequestWorkflowPlan } from "./workflows";

const mainSha = "1111111111111111111111111111111111111111";

describe("GitHub draft PR workflow execution contract", () => {
  it("leases a scoped token, executes the local workflow, and returns redacted lease metadata", async () => {
    const fakeClient = new FakeGitHubClient([
      {
        repository: "github:redohq/checkout",
        branches: { main: mainSha },
      },
    ]);
    const tokenProvider = new FakeGitHubInstallationTokenProvider({
      now: () => new Date("2026-01-02T03:04:05.000Z"),
      ttlMs: 10 * 60 * 1000,
    });
    const auths: GitHubWorkflowExecutionAuth[] = [];
    const expectedHeads: Array<string | undefined> = [];
    const client: GitHubDraftPullRequestWorkflowExecutionClient = {
      async createBranch(plan, auth) {
        auths.push(auth);
        return fakeClient.createBranch(plan);
      },
      async commitFiles(plan, auth) {
        auths.push(auth);
        expectedHeads.push(plan.expectedHeadSha);
        return fakeClient.commitFiles(plan);
      },
      async createDraftPullRequest(plan, auth) {
        auths.push(auth);
        return fakeClient.createDraftPullRequest(plan);
      },
    };
    const plan = createGitHubDraftPullRequestWorkflowPlan({
      repository: "github:redohq/checkout",
      installationId: 99,
      title: "Add retry tests",
      body: "Generated by Bek after local analysis.",
      headBranch: "bek/retry-tests",
      commitMessage: "Add retry tests",
      changes: [
        { path: "tests/retry.test.ts", content: "test('ok', () => {});\n" },
      ],
      runId: "run_123",
      requesterPrincipalId: "principal_bryson",
    });

    const result = await executeGitHubDraftPullRequestWorkflowPlan({
      plan,
      tokenProvider,
      client,
      now: () => new Date("2026-01-02T03:04:15.000Z"),
      minTokenTtlMs: 60_000,
    });

    expect(result).toMatchObject({
      type: "github.draft_pull_request_workflow_execution",
      resource: "github:redohq/checkout",
      installationId: "99",
      tokenLease: {
        installationId: "99",
        repository: { resource: "github:redohq/checkout" },
        permissions: {
          contents: "write",
          metadata: "read",
          pull_requests: "write",
        },
      },
      branch: {
        branch: "bek/retry-tests",
        commitSha: mainSha,
        createdFrom: "main",
      },
      commit: {
        branch: "bek/retry-tests",
        parentSha: mainSha,
        message: "Add retry tests",
      },
      pullRequest: {
        number: 1,
        title: "Add retry tests",
        draft: true,
      },
      runId: "run_123",
      requesterPrincipalId: "principal_bryson",
    });
    expect(expectedHeads).toEqual([mainSha]);
    expect(auths).toHaveLength(3);
    expect(
      auths.every(
        (auth) =>
          auth.installationToken.token ===
            "fake-gh-installation-token:99:github:redohq/checkout:1" &&
          auth.tokenLease.repository?.resource === "github:redohq/checkout",
      ),
    ).toBe(true);
    expect(JSON.stringify(result)).not.toContain("fake-gh-installation-token");
  });

  it("fails before client writes when the leased token does not cover the plan", async () => {
    const plan = createGitHubDraftPullRequestWorkflowPlan({
      repository: "github:redohq/checkout",
      installationId: 99,
      title: "Update checkout",
      headBranch: "bek/update-checkout",
      commitMessage: "Update checkout",
      changes: [{ path: "checkout.ts", content: "export {};\n" }],
    });
    const tokenProvider: GitHubInstallationTokenProvider = {
      async getInstallationToken() {
        return {
          type: "github.installation_token",
          installationId: "99",
          token: "secret-token",
          expiresAt: "2026-01-02T04:04:05.000Z",
          repository: {
            provider: "github",
            owner: "redohq",
            repo: "docs",
            fullName: "redohq/docs",
            resource: "github:redohq/docs",
            url: "https://github.com/redohq/docs",
          },
          permissions: { contents: "read" },
        };
      },
    };
    const client: GitHubDraftPullRequestWorkflowExecutionClient = {
      async createBranch() {
        throw new Error("createBranch should not be called");
      },
      async commitFiles() {
        throw new Error("commitFiles should not be called");
      },
      async createDraftPullRequest() {
        throw new Error("createDraftPullRequest should not be called");
      },
    };

    await expect(
      executeGitHubDraftPullRequestWorkflowPlan({
        plan,
        tokenProvider,
        client,
        now: () => new Date("2026-01-02T03:04:15.000Z"),
      }),
    ).rejects.toThrow(
      "Invalid GitHub installation token lease: GitHub installation token repository mismatch",
    );
  });
});
