import { describe, expect, it } from "vitest";
import { executeGitHubDraftPullRequestWorkflowPlan } from "./execution";
import { GitHubRestClient } from "./rest-client";
import { FakeGitHubInstallationTokenProvider } from "./tokens";
import {
  createGitHubCommitWorkflowPlan,
  createGitHubDraftPullRequestWorkflowPlan,
} from "./workflows";

describe("GitHub REST client", () => {
  it("executes a draft PR workflow against GitHub REST endpoints", async () => {
    const calls: Array<{
      method: string;
      url: string;
      body?: unknown;
      authorization?: string | null;
      userAgent?: string | null;
    }> = [];
    const fetchImpl: typeof fetch = async (input, init) => {
      const url = String(input);
      const method = init?.method ?? "GET";
      const body =
        typeof init?.body === "string" ? JSON.parse(init.body) : undefined;
      calls.push({
        method,
        url,
        ...(body === undefined ? {} : { body }),
        authorization: new Headers(init?.headers).get("authorization"),
        userAgent: new Headers(init?.headers).get("user-agent"),
      });
      if (method === "GET" && url.endsWith("/git/ref/heads/main")) {
        return jsonResponse({ object: { sha: "1".repeat(40) } });
      }
      if (
        method === "GET" &&
        url.endsWith(`/git/ref/heads/${encodeURIComponent("bek/rest-client")}`)
      ) {
        return jsonResponse({ object: { sha: "1".repeat(40) } });
      }
      if (method === "GET" && url.endsWith(`/git/commits/${"1".repeat(40)}`)) {
        return jsonResponse({
          sha: "1".repeat(40),
          tree: { sha: "2".repeat(40) },
        });
      }
      if (method === "POST" && url.endsWith("/git/refs")) {
        return jsonResponse({ ref: "refs/heads/bek/rest-client" });
      }
      if (method === "POST" && url.endsWith("/git/trees")) {
        return jsonResponse({ sha: "3".repeat(40) });
      }
      if (method === "POST" && url.endsWith("/git/commits")) {
        return jsonResponse({ sha: "4".repeat(40) });
      }
      if (method === "PATCH" && url.includes("/git/refs/heads/")) {
        return jsonResponse({ object: { sha: "4".repeat(40) } });
      }
      if (method === "POST" && url.endsWith("/pulls")) {
        return jsonResponse({
          id: 987,
          number: 42,
          title: "Add rest client",
          body: "Generated by Bek.",
          base: { ref: "main" },
          head: { ref: "bek/rest-client" },
          draft: true,
          maintainer_can_modify: true,
          html_url: "https://github.com/redohq/checkout/pull/42",
        });
      }
      if (method === "POST" && url.endsWith("/issues/42/labels")) {
        return jsonResponse({});
      }
      if (method === "POST" && url.endsWith("/pulls/42/requested_reviewers")) {
        return jsonResponse({});
      }
      if (method === "GET" && url.endsWith("/pulls/42")) {
        return jsonResponse({
          id: 987,
          number: 42,
          title: "Add rest client",
          body: "Generated by Bek.",
          base: { ref: "main" },
          head: { ref: "bek/rest-client" },
          draft: true,
          maintainer_can_modify: true,
          labels: [{ name: "automation" }],
          requested_reviewers: [{ login: "octocat" }],
          html_url: "https://github.com/redohq/checkout/pull/42",
        });
      }
      return jsonResponse({ message: `Unhandled ${method} ${url}` }, 500);
    };
    const plan = createGitHubDraftPullRequestWorkflowPlan({
      repository: "github:redohq/checkout",
      installationId: 99,
      title: "Add rest client",
      body: "Generated by Bek.",
      headBranch: "bek/rest-client",
      commitMessage: "Add GitHub REST client",
      changes: [
        { path: "src/new.ts", content: "export const ok = true;\n" },
        { path: "scripts/run.sh", content: "#!/bin/sh\n", executable: true },
        { path: "old.txt", deletion: true },
      ],
      labels: ["automation"],
      reviewers: ["octocat"],
    });

    const result = await executeGitHubDraftPullRequestWorkflowPlan({
      plan,
      tokenProvider: new FakeGitHubInstallationTokenProvider({
        now: () => new Date("2026-01-02T03:04:05.000Z"),
      }),
      client: new GitHubRestClient({
        apiBaseUrl: "https://api.github.test",
        fetch: fetchImpl,
        userAgent: "bek-test-suite",
      }),
      now: () => new Date("2026-01-02T03:04:10.000Z"),
    });

    expect(result.pullRequest).toMatchObject({
      number: 42,
      htmlUrl: "https://github.com/redohq/checkout/pull/42",
      labels: ["automation"],
      reviewers: ["octocat"],
    });
    expect(calls.map((call) => `${call.method} ${call.url}`)).toEqual([
      "GET https://api.github.test/repos/redohq/checkout/git/ref/heads/main",
      "POST https://api.github.test/repos/redohq/checkout/git/refs",
      "GET https://api.github.test/repos/redohq/checkout/git/ref/heads/bek%2Frest-client",
      `GET https://api.github.test/repos/redohq/checkout/git/commits/${"1".repeat(40)}`,
      "POST https://api.github.test/repos/redohq/checkout/git/trees",
      "POST https://api.github.test/repos/redohq/checkout/git/commits",
      "PATCH https://api.github.test/repos/redohq/checkout/git/refs/heads/bek%2Frest-client",
      "POST https://api.github.test/repos/redohq/checkout/pulls",
      "POST https://api.github.test/repos/redohq/checkout/issues/42/labels",
      "POST https://api.github.test/repos/redohq/checkout/pulls/42/requested_reviewers",
      "GET https://api.github.test/repos/redohq/checkout/pulls/42",
    ]);
    expect(
      calls.every((call) => call.authorization?.startsWith("Bearer ")),
    ).toBe(true);
    expect(calls.every((call) => call.userAgent === "bek-test-suite")).toBe(
      true,
    );
    expect(calls.find((call) => call.url.endsWith("/git/trees"))?.body).toEqual(
      {
        base_tree: "2".repeat(40),
        tree: [
          {
            path: "src/new.ts",
            mode: "100644",
            type: "blob",
            content: "export const ok = true;\n",
          },
          {
            path: "scripts/run.sh",
            mode: "100755",
            type: "blob",
            content: "#!/bin/sh\n",
          },
          { path: "old.txt", mode: "100644", type: "blob", sha: null },
        ],
      },
    );
  });

  it("redacts GitHub tokens from failed REST responses", async () => {
    const client = new GitHubRestClient({
      apiBaseUrl: "https://api.github.test",
      fetch: async () =>
        jsonResponse(
          {
            message:
              "bad token ghp_abcdefghijklmnopqrstuvwxyz1234567890 Bearer also-secret ghs_secret-installation-token",
          },
          403,
          "Forbidden",
        ),
    });
    const plan = createGitHubDraftPullRequestWorkflowPlan({
      repository: "github:redohq/checkout",
      installationId: 99,
      title: "Add rest client",
      headBranch: "bek/rest-client",
      commitMessage: "Add GitHub REST client",
      changes: [{ path: "src/new.ts", content: "export const ok = true;\n" }],
    });

    let thrown: unknown;
    try {
      await client.createBranch(plan.branch, {
        installationToken: {
          type: "github.installation_token",
          installationId: "99",
          token: "ghs_secret-installation-token",
          expiresAt: "2026-01-02T04:04:05.000Z",
          repository: plan.repository,
          permissions: {
            contents: "write",
            metadata: "read",
            pull_requests: "write",
          },
        },
        tokenLease: {
          type: "github.installation_token_lease",
          installationId: "99",
          repository: plan.repository,
          permissions: {
            contents: "write",
            metadata: "read",
            pull_requests: "write",
          },
          expiresAt: "2026-01-02T04:04:05.000Z",
        },
      });
    } catch (error) {
      thrown = error;
    }
    const message = thrown instanceof Error ? thrown.message : String(thrown);
    expect(message).toContain("[redacted:github-token]");
    expect(message).not.toContain("ghp_abcdefghijklmnopqrstuvwxyz1234567890");
    expect(message).not.toContain("also-secret");
    expect(message).not.toContain("ghs_secret-installation-token");
  });

  it("stops before write endpoints when the expected branch head is stale", async () => {
    const calls: Array<{ method: string; url: string }> = [];
    const client = new GitHubRestClient({
      apiBaseUrl: "https://api.github.test",
      fetch: async (input, init) => {
        const url = String(input);
        const method = init?.method ?? "GET";
        calls.push({ method, url });
        if (method === "GET" && url.endsWith("/git/ref/heads/bek%2Fstale")) {
          return jsonResponse({ object: { sha: "1".repeat(40) } });
        }
        return jsonResponse({ message: "unexpected call" }, 500);
      },
    });
    const plan = createGitHubCommitWorkflowPlan({
      repository: "github:redohq/checkout",
      installationId: 99,
      branch: "bek/stale",
      message: "Update stale branch",
      expectedHeadSha: "2".repeat(40),
      changes: [{ path: "src/new.ts", content: "export const ok = true;\n" }],
    });

    await expect(
      client.commitFiles(plan, {
        installationToken: {
          type: "github.installation_token",
          installationId: "99",
          token: "ghs_secret-installation-token",
          expiresAt: "2026-01-02T04:04:05.000Z",
          repository: plan.repository,
          permissions: {
            contents: "write",
            metadata: "read",
            pull_requests: "write",
          },
        },
        tokenLease: {
          type: "github.installation_token_lease",
          installationId: "99",
          repository: plan.repository,
          permissions: {
            contents: "write",
            metadata: "read",
            pull_requests: "write",
          },
          expiresAt: "2026-01-02T04:04:05.000Z",
        },
      }),
    ).rejects.toThrow("expected commit SHA");
    expect(calls).toEqual([
      {
        method: "GET",
        url: "https://api.github.test/repos/redohq/checkout/git/ref/heads/bek%2Fstale",
      },
    ]);
  });

  it("treats an existing branch at the base SHA as an idempotent success", async () => {
    const calls: Array<{ method: string; url: string; body?: unknown }> = [];
    const client = new GitHubRestClient({
      apiBaseUrl: "https://api.github.test",
      fetch: async (input, init) => {
        const url = String(input);
        const method = init?.method ?? "GET";
        const body =
          typeof init?.body === "string" ? JSON.parse(init.body) : undefined;
        calls.push({ method, url, ...(body === undefined ? {} : { body }) });
        if (method === "GET" && url.endsWith("/git/ref/heads/main")) {
          return jsonResponse({ object: { sha: "1".repeat(40) } });
        }
        if (method === "POST" && url.endsWith("/git/refs")) {
          return jsonResponse({ message: "Reference already exists" }, 422);
        }
        if (
          method === "GET" &&
          url.endsWith(`/git/ref/heads/${encodeURIComponent("bek/retry")}`)
        ) {
          return jsonResponse({ object: { sha: "1".repeat(40) } });
        }
        return jsonResponse({ message: "unexpected call" }, 500);
      },
    });
    const plan = createGitHubDraftPullRequestWorkflowPlan({
      repository: "github:redohq/checkout",
      installationId: 99,
      title: "Retry branch",
      headBranch: "bek/retry",
      commitMessage: "Retry branch",
      changes: [{ path: "src/new.ts", content: "export const ok = true;\n" }],
    });

    await expect(
      client.createBranch(plan.branch, authFor(plan.repository)),
    ).resolves.toMatchObject({
      branch: "bek/retry",
      commitSha: "1".repeat(40),
    });
    expect(calls.map((call) => `${call.method} ${call.url}`)).toEqual([
      "GET https://api.github.test/repos/redohq/checkout/git/ref/heads/main",
      "POST https://api.github.test/repos/redohq/checkout/git/refs",
      "GET https://api.github.test/repos/redohq/checkout/git/ref/heads/bek%2Fretry",
    ]);
  });

  it("fails an existing branch retry when the branch points at a different SHA", async () => {
    const client = new GitHubRestClient({
      apiBaseUrl: "https://api.github.test",
      fetch: async (input, init) => {
        const url = String(input);
        const method = init?.method ?? "GET";
        if (method === "GET" && url.endsWith("/git/ref/heads/main")) {
          return jsonResponse({ object: { sha: "1".repeat(40) } });
        }
        if (method === "POST" && url.endsWith("/git/refs")) {
          return jsonResponse({ message: "Reference already exists" }, 422);
        }
        if (
          method === "GET" &&
          url.endsWith(`/git/ref/heads/${encodeURIComponent("bek/conflict")}`)
        ) {
          return jsonResponse({ object: { sha: "2".repeat(40) } });
        }
        return jsonResponse({ message: "unexpected call" }, 500);
      },
    });
    const plan = createGitHubDraftPullRequestWorkflowPlan({
      repository: "github:redohq/checkout",
      installationId: 99,
      title: "Conflict branch",
      headBranch: "bek/conflict",
      commitMessage: "Conflict branch",
      changes: [{ path: "src/new.ts", content: "export const ok = true;\n" }],
    });

    await expect(
      client.createBranch(plan.branch, authFor(plan.repository)),
    ).rejects.toThrow(`already exists at ${"2".repeat(40)}`);
  });

  it("reuses an existing open pull request and returns observed metadata", async () => {
    const calls: Array<{ method: string; url: string; body?: unknown }> = [];
    const client = new GitHubRestClient({
      apiBaseUrl: "https://api.github.test",
      fetch: async (input, init) => {
        const url = String(input);
        const method = init?.method ?? "GET";
        const body =
          typeof init?.body === "string" ? JSON.parse(init.body) : undefined;
        calls.push({ method, url, ...(body === undefined ? {} : { body }) });
        if (method === "POST" && url.endsWith("/pulls")) {
          return jsonResponse(
            { message: "A pull request already exists for this branch" },
            422,
          );
        }
        if (method === "GET" && url.includes("/pulls?")) {
          return jsonResponse([
            {
              id: 987,
              number: 42,
              title: "Existing PR",
              body: "Created before retry.",
              base: { ref: "main" },
              head: { ref: "bek/rest-client" },
              draft: true,
              maintainer_can_modify: true,
              html_url: "https://github.com/redohq/checkout/pull/42",
            },
          ]);
        }
        if (method === "POST" && url.endsWith("/issues/42/labels")) {
          return jsonResponse([{ name: "automation" }]);
        }
        if (
          method === "POST" &&
          url.endsWith("/pulls/42/requested_reviewers")
        ) {
          return jsonResponse({
            requested_reviewers: [{ login: "octocat" }],
          });
        }
        if (method === "GET" && url.endsWith("/pulls/42")) {
          return jsonResponse({
            id: 987,
            number: 42,
            title: "Existing PR",
            body: "Created before retry.",
            base: { ref: "main" },
            head: { ref: "bek/rest-client" },
            draft: true,
            maintainer_can_modify: true,
            labels: [{ name: "automation" }, { name: "existing" }],
            requested_reviewers: [{ login: "octocat" }],
            html_url: "https://github.com/redohq/checkout/pull/42",
          });
        }
        return jsonResponse({ message: "unexpected call" }, 500);
      },
    });
    const plan = createGitHubDraftPullRequestWorkflowPlan({
      repository: "github:redohq/checkout",
      installationId: 99,
      title: "Add rest client",
      headBranch: "bek/rest-client",
      commitMessage: "Add GitHub REST client",
      changes: [{ path: "src/new.ts", content: "export const ok = true;\n" }],
      labels: ["automation"],
      reviewers: ["octocat"],
    });

    const result = await client.createDraftPullRequest(
      plan,
      authFor(plan.repository),
    );

    expect(result).toMatchObject({
      number: 42,
      title: "Existing PR",
      labels: ["automation", "existing"],
      reviewers: ["octocat"],
    });
    expect(calls.map((call) => `${call.method} ${call.url}`)).toEqual([
      "POST https://api.github.test/repos/redohq/checkout/pulls",
      "GET https://api.github.test/repos/redohq/checkout/pulls?state=open&head=redohq%3Abek%2Frest-client&base=main",
      "POST https://api.github.test/repos/redohq/checkout/issues/42/labels",
      "POST https://api.github.test/repos/redohq/checkout/pulls/42/requested_reviewers",
      "GET https://api.github.test/repos/redohq/checkout/pulls/42",
    ]);
  });
});

function authFor(repository: {
  resource: string;
  owner: string;
  repo: string;
}) {
  return {
    installationToken: {
      type: "github.installation_token" as const,
      installationId: "99",
      token: "ghs_secret-installation-token",
      expiresAt: "2026-01-02T04:04:05.000Z",
      repository,
      permissions: {
        contents: "write" as const,
        metadata: "read" as const,
        pull_requests: "write" as const,
      },
    },
    tokenLease: {
      type: "github.installation_token_lease" as const,
      installationId: "99",
      repository,
      permissions: {
        contents: "write" as const,
        metadata: "read" as const,
        pull_requests: "write" as const,
      },
      expiresAt: "2026-01-02T04:04:05.000Z",
    },
  };
}

function jsonResponse(
  body: unknown,
  status = 200,
  statusText = "OK",
): Response {
  return new Response(JSON.stringify(body), {
    status,
    statusText,
    headers: { "content-type": "application/json" },
  });
}
