import { describe, expect, it } from "vitest";
import {
  createGitHubBranchWorkflowPlan,
  createGitHubCommitWorkflowPlan,
  createGitHubDraftPullRequestWorkflowApprovalPayload,
  createGitHubDraftPullRequestWorkflowPlan,
  createGitHubDraftPullRequestWorkflowPlanFromApprovalPayload,
  normalizeCommitChanges,
} from "./workflows";

describe("GitHub workflow plans", () => {
  it("creates branch, commit, and draft PR workflow plans for local execution", () => {
    const plan = createGitHubDraftPullRequestWorkflowPlan({
      repository: "RedoHQ/Checkout",
      installationId: "789",
      repositoryId: "112233",
      title: "Add retry tests",
      body: "Generated by Bek after local analysis.",
      baseBranch: "main",
      headBranch: "bek/retry-tests",
      commitMessage: "Add retry tests",
      changes: [
        {
          path: "tests/retry.test.ts",
          content: "expect(true).toBe(true);\n",
        },
      ],
      labels: ["tests"],
      reviewers: ["bryson"],
      runId: "run_123",
      requesterPrincipalId: "principal_bryson",
    });

    expect(plan).toMatchObject({
      type: "github.draft_pull_request_workflow_plan",
      visibleAgentHandle: "@bek",
      resource: "github:redohq/checkout",
      installationId: "789",
      repositoryId: 112233,
      steps: [
        "mint_installation_token",
        "create_branch",
        "commit_changes",
        "open_draft_pull_request",
      ],
      tokenRequest: {
        installationId: "789",
        repositoryIds: [112233],
        permissions: {
          contents: "write",
          metadata: "read",
          pull_requests: "write",
        },
      },
      branch: {
        capability: "github.branch",
        baseBranch: "main",
        headBranch: "bek/retry-tests",
      },
      commit: {
        capability: "github.branch",
        branch: "bek/retry-tests",
        message: "Add retry tests",
      },
      pullRequest: {
        capability: "github.pr",
        title: "Add retry tests",
        draft: true,
      },
      approvalHashInput: {
        action: "github.pr",
        installationId: "789",
        repositoryId: 112233,
        resource: "github:redohq/checkout",
      },
      runId: "run_123",
      requesterPrincipalId: "principal_bryson",
    });
  });

  it("creates standalone branch and commit plans", () => {
    expect(
      createGitHubBranchWorkflowPlan({
        repository: "github:redohq/checkout",
        installationId: 12,
        headBranch: "bek/standalone",
      }),
    ).toMatchObject({
      type: "github.branch_workflow_plan",
      baseBranch: "main",
      headBranch: "bek/standalone",
      approval: {
        action: "github.branch",
        risk: "write_draft",
      },
    });

    expect(
      createGitHubCommitWorkflowPlan({
        repository: "github:redohq/checkout",
        installationId: 12,
        branch: "bek/standalone",
        message: "Update docs",
        changes: [{ path: "docs/readme.md", content: "# Docs\n" }],
      }),
    ).toMatchObject({
      type: "github.commit_workflow_plan",
      branch: "bek/standalone",
      message: "Update docs",
    });
  });

  it("rejects unsafe commit changes before a client sees them", () => {
    expect(() => normalizeCommitChanges([])).toThrow("at least one");
    expect(() =>
      normalizeCommitChanges([{ path: "../secret", content: "nope" }]),
    ).toThrow("safe relative path");
    expect(() =>
      normalizeCommitChanges([{ path: "a.txt", deletion: true, content: "" }]),
    ).toThrow("cannot include content");
    expect(() =>
      normalizeCommitChanges([
        { path: "a.txt", content: "one" },
        { path: "a.txt", content: "two" },
      ]),
    ).toThrow("duplicate path");
  });
});

describe("GitHub draft PR deterministic head branch", () => {
  const basePlanInput = {
    repository: "github:redohq/checkout",
    installationId: 99,
    title: "Add retry tests for the checkout flow",
    body: "Generated by Bek after local analysis.",
    commitMessage: "Add retry tests",
    changes: [{ path: "tests/retry.test.ts", content: "ok\n" }],
    runId: "run_123",
    requesterPrincipalId: "principal_bryson",
  };

  it("derives a deterministic branch from the plan hash + title slug when headBranch is omitted", () => {
    const a = createGitHubDraftPullRequestWorkflowPlan({ ...basePlanInput });
    const b = createGitHubDraftPullRequestWorkflowPlan({ ...basePlanInput });

    // (a) stable across two identical plan creations.
    expect(a.pullRequest.headBranch).toBe(b.pullRequest.headBranch);
    expect(a.planHashBinding.hash).toBe(b.planHashBinding.hash);

    // Branch is derived (bek/ prefix), carries a title slug, and is internally
    // consistent across the branch/commit/PR sub-plans.
    expect(a.pullRequest.headBranch.startsWith("bek/")).toBe(true);
    expect(a.pullRequest.headBranch).toContain("retry");
    expect(a.branch.headBranch).toBe(a.pullRequest.headBranch);
    expect(a.commit.branch).toBe(a.pullRequest.headBranch);
    expect(a.branchResolution.decision).toBe("create_new");
  });

  it("changes the derived branch when the diff changes", () => {
    const a = createGitHubDraftPullRequestWorkflowPlan({ ...basePlanInput });
    const b = createGitHubDraftPullRequestWorkflowPlan({
      ...basePlanInput,
      changes: [{ path: "tests/other.test.ts", content: "ok\n" }],
    });
    expect(a.pullRequest.headBranch).not.toBe(b.pullRequest.headBranch);
  });

  it("preserves an explicit headBranch and its plan hash exactly", () => {
    const explicit = createGitHubDraftPullRequestWorkflowPlan({
      ...basePlanInput,
      headBranch: "bek/explicit-branch",
    });
    expect(explicit.pullRequest.headBranch).toBe("bek/explicit-branch");
    expect(explicit.branch.headBranch).toBe("bek/explicit-branch");
    expect(explicit.branchResolution.decision).toBe("create_new");
  });

  it("(b) reuses a colliding branch with the same plan hash", () => {
    const planned = createGitHubDraftPullRequestWorkflowPlan({
      ...basePlanInput,
    });
    const reused = createGitHubDraftPullRequestWorkflowPlan({
      ...basePlanInput,
      existingBranches: [
        {
          name: planned.pullRequest.headBranch,
          planHash: planned.planHashBinding.hash,
        },
      ],
    });
    expect(reused.branchResolution.decision).toBe("reuse_existing");
    expect(reused.pullRequest.headBranch).toBe(planned.pullRequest.headBranch);
  });

  it("(c) surfaces a conflict for a colliding branch with a different plan hash", () => {
    const planned = createGitHubDraftPullRequestWorkflowPlan({
      ...basePlanInput,
    });
    expect(() =>
      createGitHubDraftPullRequestWorkflowPlan({
        ...basePlanInput,
        existingBranches: [
          {
            name: planned.pullRequest.headBranch,
            planHash: "some-other-plan-hash",
          },
        ],
      }),
    ).toThrow("conflicts with an existing branch");
  });

  it("conflicts when an existing PR for the branch was opened for a different plan", () => {
    const planned = createGitHubDraftPullRequestWorkflowPlan({
      ...basePlanInput,
      headBranch: "bek/explicit-branch",
    });
    expect(() =>
      createGitHubDraftPullRequestWorkflowPlan({
        ...basePlanInput,
        headBranch: "bek/explicit-branch",
        existingPullRequests: [
          {
            number: 12,
            headBranch: planned.pullRequest.headBranch,
            planHash: "different-plan",
          },
        ],
      }),
    ).toThrow("conflicts with an existing branch or pull request");
  });

  it("(d) round-trips the approval hash for a derived branch (plan -> payload -> plan)", () => {
    const plan = createGitHubDraftPullRequestWorkflowPlan({ ...basePlanInput });
    const payload = createGitHubDraftPullRequestWorkflowApprovalPayload(plan);

    // The payload carries the resolved (derived) head branch.
    expect(payload.pullRequest.headBranch).toBe(plan.pullRequest.headBranch);
    expect(payload.branch.headBranch).toBe(plan.pullRequest.headBranch);

    // Re-deriving the plan from the approval payload reproduces the same head
    // branch, approval hash input, and plan hash binding.
    const rebuilt =
      createGitHubDraftPullRequestWorkflowPlanFromApprovalPayload(payload);
    expect(rebuilt.pullRequest.headBranch).toBe(plan.pullRequest.headBranch);
    expect(rebuilt.approvalHashInput).toEqual(plan.approvalHashInput);
    expect(rebuilt.planHashBinding.hash).toBe(plan.planHashBinding.hash);
    expect(
      createGitHubDraftPullRequestWorkflowApprovalPayload(rebuilt),
    ).toEqual(payload);
  });
});
