import { describe, expect, it } from "vitest";
import {
  createGitHubBranchWorkflowPlan,
  createGitHubCommitWorkflowPlan,
  createGitHubDraftPullRequestWorkflowPlan,
  normalizeCommitChanges,
} from "./workflows";

describe("GitHub workflow plans", () => {
  it("creates branch, commit, and draft PR workflow plans for local execution", () => {
    const plan = createGitHubDraftPullRequestWorkflowPlan({
      repository: "RedoHQ/Checkout",
      installationId: "789",
      title: "Add retry tests",
      body: "Generated by Bek after local analysis.",
      baseBranch: "main",
      headBranch: "bek/retry-tests",
      commitMessage: "Add retry tests",
      changes: [
        {
          path: "tests/retry.test.ts",
          content: "expect(true).toBe(true);\n",
        },
      ],
      labels: ["tests"],
      reviewers: ["bryson"],
      runId: "run_123",
      requesterPrincipalId: "principal_bryson",
    });

    expect(plan).toMatchObject({
      type: "github.draft_pull_request_workflow_plan",
      visibleAgentHandle: "@bek",
      resource: "github:redohq/checkout",
      installationId: "789",
      steps: [
        "mint_installation_token",
        "create_branch",
        "commit_changes",
        "open_draft_pull_request",
      ],
      tokenRequest: {
        installationId: "789",
        permissions: {
          contents: "write",
          metadata: "read",
          pull_requests: "write",
        },
      },
      branch: {
        capability: "github.branch",
        baseBranch: "main",
        headBranch: "bek/retry-tests",
      },
      commit: {
        capability: "github.branch",
        branch: "bek/retry-tests",
        message: "Add retry tests",
      },
      pullRequest: {
        capability: "github.pr",
        title: "Add retry tests",
        draft: true,
      },
      approvalHashInput: {
        action: "github.pr",
        installationId: "789",
        resource: "github:redohq/checkout",
      },
      runId: "run_123",
      requesterPrincipalId: "principal_bryson",
    });
  });

  it("creates standalone branch and commit plans", () => {
    expect(
      createGitHubBranchWorkflowPlan({
        repository: "github:redohq/checkout",
        installationId: 12,
        headBranch: "bek/standalone",
      }),
    ).toMatchObject({
      type: "github.branch_workflow_plan",
      baseBranch: "main",
      headBranch: "bek/standalone",
      approval: {
        action: "github.branch",
        risk: "write_draft",
      },
    });

    expect(
      createGitHubCommitWorkflowPlan({
        repository: "github:redohq/checkout",
        installationId: 12,
        branch: "bek/standalone",
        message: "Update docs",
        changes: [{ path: "docs/readme.md", content: "# Docs\n" }],
      }),
    ).toMatchObject({
      type: "github.commit_workflow_plan",
      branch: "bek/standalone",
      message: "Update docs",
    });
  });

  it("rejects unsafe commit changes before a client sees them", () => {
    expect(() => normalizeCommitChanges([])).toThrow("at least one");
    expect(() =>
      normalizeCommitChanges([{ path: "../secret", content: "nope" }]),
    ).toThrow("safe relative path");
    expect(() =>
      normalizeCommitChanges([{ path: "a.txt", deletion: true, content: "" }]),
    ).toThrow("cannot include content");
    expect(() =>
      normalizeCommitChanges([
        { path: "a.txt", content: "one" },
        { path: "a.txt", content: "two" },
      ]),
    ).toThrow("duplicate path");
  });
});
